'use client'

import { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'es' | 'en' | 'fr' | 'pt'

interface Translations {
  [key: string]: {
    [key: string]: string
  }
}

const translations: Translations = {
  es: {
    'auth.logout_confirm.title': '¿Cerrar Sesión?',
    'auth.logout_confirm.description': '¿Estás seguro de que quieres cerrar sesión? Tendrás que iniciar sesión nuevamente para acceder a tu cuenta.',
    'auth.logout_confirm.cancel': 'Cancelar',
    'auth.logout_confirm.confirm': 'Cerrar Sesión',
    'nav.login': 'Iniciar Sesión',
    'nav.cart': 'Carrito',
    'nav.home': 'Inicio',
    'nav.shop': 'Tienda',
    'nav.discounts': 'Descuentos',
    'hero.title': 'El Futuro de la Moda',
    'hero.subtitle': 'Colección curada de streetwear distópico y estética cyberpunk.',
    'product.new': 'NUEVO',
    'products.add': 'Agregar',
    'auth.welcome': 'Bienvenido a ThunderXis',
    'auth.subtitle': 'Ingresa tus credenciales para acceder',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Registrarse',
    'auth.no_account': '¿No tienes una cuenta?',
    'auth.create': 'Crea una cuenta',
    'auth.name': 'Nombre Completo',
    // New
    'home.new_arrivals': 'Nuevos Lanzamientos',
    'home.new_drops': 'Nuevos',
    'home.view_all': 'Ver Todo',
    'filters.title': 'Filtros',
    'filters.gender': 'Género',
    'filters.men': 'Hombres',
    'filters.women': 'Mujeres',
    'filters.categories': 'Categorías',
    'cat.hoodies': 'Hoodies',
    'cat.tshirts': 'Camisetas',
    'cat.pants': 'Pantalones',
    'cat.footwear': 'Calzado',
    'cat.accessories': 'Accesorios',
    'hero.cta': 'Ver Colección',
    // Footer
    'footer.about': 'Sobre Nosotros',
    'footer.description': 'Redefiniendo el streetwear con una estética futurista y materiales premium.',
    'footer.shop': 'Tienda',
    'footer.help': 'Ayuda',
    'footer.legal': 'Legal',
    'footer.links.men': 'Hombres',
    'footer.links.women': 'Mujeres',
    'footer.links.sale': 'Ofertas',
    'footer.help.shipping': 'Envíos',
    'footer.help.returns': 'Devoluciones',
    'footer.help.contact': 'Contacto',
    'footer.newsletter': 'Suscríbete',
    'footer.newsletter.desc': 'Recibe las últimas novedades y ofertas exclusivas.',
    'footer.rights': 'Todos los derechos reservados.',
    // WhatsApp
    'whatsapp.chat': 'Chatea con nosotros',
    // Checkout
    'checkout.title': 'Finalizar Compra',
    'checkout.shipping': 'Información de Envío',
    'checkout.name': 'Nombre Completo',
    'checkout.address': 'Dirección de Envío',
    'checkout.city': 'Ciudad',
    'checkout.phone': 'Celular / Teléfono',
    'checkout.placeholder_name': 'Ej: Juan Pérez',
    'checkout.placeholder_address': 'Ej: Calle 123 # 45-67',
    'checkout.placeholder_phone': 'Ej: 300 123 4567',
    'checkout.summary': 'Resumen del Pedido',
    'checkout.subtotal': 'Subtotal',
    'checkout.shipping_cost': 'Costo de Envío',
    'checkout.total': 'Total a Pagar',
    'checkout.pay': 'Pagar con Mercado Pago',
    'checkout.processing': 'Procesando...',
    'checkout.error': 'Error al procesar el pedido',
    'checkout.select_city': 'Selecciona tu ciudad',
    'checkout.select_city_calc': 'Selecciona tu ciudad para calcular envío',
    'filters.banner.title': 'Oferta de Invierno',
    'filters.banner.desc': 'Hasta 50% de descuento en artículos seleccionados.',
    'filters.banner.cta': 'Ver Ofertas',
    'auth.premium': 'Calidad Premium',
    'auth.premium.desc': 'Materiales seleccionados para durabilidad y confort.',
    'auth.style': 'Estilo Urbano',
    'auth.style.desc': 'Diseños exclusivos que definen tendencias.',
    'auth.join.desc': 'Únete a la comunidad de moda más exclusiva.',
    'auth.have_account': '¿Ya tienes cuenta?',
    'auth.logout': 'Cerrar Sesión',
    'cart.empty': 'Tu carrito está vacío.',
    'cart.size': 'Talla',
    'cart.login_required': 'Por favor inicia sesión para completar tu orden.',
    'checkout.secure_payment': 'Pagos seguros vía Mercado Pago',
    'product.not_found': 'Producto no encontrado',
    'product.select_size': 'Selecciona Talla',
    'product.shipping_info': 'Envío gratis en compras superiores a $200.000',
    'product.return_policy': 'Política de devolución de 30 días',
    'nav.account': 'Cuenta',
    'nav.orders': 'Mis Pedidos',
    'nav.favorites': 'Favoritos',
    'nav.menu': 'Menú',
    'nav.language': 'Idioma',
    'favorites.login_msg': 'Por favor inicia sesión para ver tus favoritos.',
    'favorites.empty': 'No tienes productos guardados aún.',
    'favorites.browse': 'Explorar Tienda',
    'favorites.added': 'Agregado a favoritos',
    'favorites.removed': 'Eliminado de favoritos',
    'favorites.error_add': 'Error al agregar a favoritos',
    'favorites.error_remove': 'Error al eliminar de favoritos',
    'favorites.login_required': 'Inicia sesión para guardar favoritos',
    'checkout.redirecting': 'Redirigiendo al pago...',
    'checkout.init_failed': 'Error al iniciar pago',
    'checkout.missing_fields': 'Faltan campos de envío',
    'cart.added_success': 'Agregado al carrito',
    'footer.address': 'Bogotá, Colombia',
    'products.details': 'Ver Detalles',
    'product.quantity': 'Cantidad',
    'product.size_guide': 'Guía de tallas',
    'product.available_stock': 'unidades disponibles',
    'product.out_of_stock': 'Agotado',
    'discounts.limited_time': 'Tiempo Limitado',
    'discounts.no_active': 'No hay ofertas activas',
    'discounts.updating_inventory': 'Estamos actualizando nuestro inventario. Vuelve pronto.',
    'discounts.back_to_shop': 'Volver a la Tienda',
    'shop.no_results': 'No se encontraron productos con estos filtros.',
    'shop.clear_filters': 'Limpiar Filtros',
    'nav.dashboard': 'Dashboard',
    'nav.orders_tooltip': 'Inicia sesión para ver pedidos',
    'footer.subscribe_btn': 'Suscribirse',
    'dash.create_product': 'Crear Producto',
    'dash.name': 'Nombre del Producto',
    'dash.price': 'Precio',
    'dash.desc': 'Descripción',
    'dash.rating': 'Calificación',
    'dash.img': 'URL de Imagen',
    'dash.cat': 'Categoría',
    'dash.gender': 'Género',
    'dash.stock': 'Inventario',
    'dash.create_btn': 'Publicar Producto',
    'dash.success': 'Producto creado exitosamente',
    'dash.users': 'Usuarios',
    'dash.products': 'Productos',
    'dash.analytics': 'Analíticas',
    'dash.orders': 'Pedidos',
    // Dashboard comprehensive translations
    'dash.user_management': 'Gestión de Usuarios',
    'dash.user_desc': 'Administrar roles y permisos de usuarios',
    'dash.search': 'Buscar',
    'dash.total_users': 'Total de Usuarios',
    'dash.owners': 'Propietarios',
    'dash.regular_users': 'Usuarios Regulares',
    'dash.role': 'Rol',
    'dash.joined': 'Registrado',
    'dash.actions': 'Acciones',
    'dash.delete_user': 'Eliminar usuario',
    'dash.click_toggle': 'Click para cambiar',
    'dash.no_users': 'No se encontraron usuarios',
    'dash.warning_zone': 'Zona de administración sensible',
    'dash.role_warning': 'Solo cambia roles a usuarios de confianza. El rol Owner tiene acceso completo al dashboard.',
    // Orders
    'dash.orders_management': 'Gestión de Pedidos',
    'dash.orders_desc': 'Administrar envíos y cumplimiento de pedidos',
    'dash.total_orders': 'Total de Pedidos',
    'dash.all': 'Todos',
    'dash.pending': 'Pendiente',
    'dash.paid': 'Pagado',
    'dash.shipped': 'Enviado',
    'dash.delivered': 'Entregado',
    'dash.cancelled': 'Cancelado',
    'dash.customer': 'Cliente',
    'dash.date': 'Fecha',
    'dash.amount': 'Monto',
    'dash.status': 'Estado',
    'dash.phone': 'Teléfono',
    'dash.city': 'Ciudad',
    'dash.address': 'Dirección',
    'dash.mark_paid': 'Marcar como Pagado',
    'dash.ship_order': 'Enviar Pedido',
    'dash.mark_delivered': 'Marcar como Entregado',
    'dash.no_orders': 'No hay pedidos aún',
    // Products
    'dash.add_product': 'Agregar Producto',
    'dash.product_management': 'Gestión de Productos',
    'dash.manage_inventory': 'Administrar inventario de la tienda',
    'dash.search_products': 'Buscar productos...',
    'dash.product_name': 'Nombre del Producto',
    'dash.category': 'Categoría',
    'dash.new_product': 'Nuevo Producto',
    'dash.edit_product': 'Editar Producto',
    'dash.product_details': 'Detalles del producto',
    'dash.basic_info': 'Información Básica',
    'dash.select_category': 'Seleccionar categoría',
    'dash.available_sizes': 'Tallas Disponibles',
    'dash.colors': 'Colores',
    'dash.click_add_colors': 'Click para agregar colores',
    'dash.product_images': 'Imágenes del Producto',
    'dash.click_upload': 'Click para subir imágenes',
    'dash.upload_limit': 'PNG, JPG hasta 5MB',
    'dash.mark_new': 'Marcar como producto NUEVO',
    'dash.cancel': 'Cancelar',
    'dash.save_product': 'Guardar Producto',
    'dash.uploading': 'Subiendo...',
    'dash.no_products': 'No se encontraron productos',
    'dash.add_first': 'Añade tu primer producto!',
    'dash.delete_confirm': '¿Estás seguro de eliminar este producto?',
    'dash.sale_price_label': 'Oferta (Opcional)',
    'dash.sale_price_placeholder': 'Precio de oferta...',
    'dash.filter_rating': 'Calificación Min',
    'dash.rating_label': 'Calificación Inicial (Fija)',
    'dash.rating_help': 'Estrellas que se mostrarán por defecto',

    'dash.error_save_product': 'Error al guardar el producto',
    'dash.error_delete_product': 'Error al eliminar producto',
    // Navbar
    'dash.notifications': 'Notificaciones',
    'dash.language': 'Idioma',
    'dash.profile': 'Perfil',
    'dash.settings': 'Configuración',
    'dash.administrator': 'Administrador',
    'dash.export': 'Exportar',
    'dash.export_csv': 'Exportar CSV',
    'dash.daily': 'Diario',
    'dash.weekly': 'Semanal',
    'dash.monthly': 'Mensual',
    'dash.monitor_performance': 'Monitorea el rendimiento de tu negocio',
    'dash.revenue': 'Ingresos',
    'dash.revenue_trend': 'Tendencia de Ingresos',
    'dash.orders_volume': 'Volumen de Pedidos',
    'dash.recent_orders': 'Pedidos Recientes',
    'dash.view_all': 'Ver Todos',
    'dash.total_sales': 'Ventas Totales',
    'dash.customers': 'Clientes',
    'dash.avg_order': 'Pedido Promedio',
    'dash.order_id': 'ID de Pedido',
    // Additional Dashboard Translations
    'dash.access_denied': 'Acceso Denegado',
    'dash.no_permission': 'No tienes permiso para ver esta página.',
    'dash.user_label': 'Usuario:',
    'dash.role_label': 'Rol:',
    'dash.required_role': 'Rol Requerido:',
    'dash.go_home': 'Ir al Inicio',
    'dash.admin': 'Admin',
    'dash.panel': 'Panel de Dashboard',
    'dash.no_data': 'Sin datos',
    'dash.search_placeholder': 'Buscar...',
    'dash.user': 'Usuario',
    'dash.search_users': 'Buscar usuarios...',
    'dash.no_users_search': 'No se encontraron usuarios que coincidan con tu búsqueda',
    'dash.role_change_confirm': '¿Estás seguro de cambiar este usuario a {role}?',
    'dash.error_role_change': 'Error cambiando el rol',
    'dash.delete_confirm_user': '⚠️ ¿Estás SEGURO de eliminar la cuenta de {email}?\n\nEsta acción NO SE PUEDE DESHACER.',
    'dash.error_delete_user': 'Error eliminando usuario',
    'dash.search_orders': 'Buscar por ID o cliente...',
    'dash.no_orders_search': 'No se encontraron pedidos que coincidan con tu búsqueda',
    'dash.customer_label': 'Cliente:',
    'dash.date_label': 'Fecha:',
    'dash.phone_label': 'Teléfono:',
    'dash.city_label': 'Ciudad:',
    'dash.address_label': 'Dirección:',
    'dash.error_update_order': 'Error actualizando estado del pedido',
    'dash.owner': 'Propietario',
    'dash.confirm_status_title': 'Confirmar Cambio',
    'dash.confirm_status_desc': '¿Estás seguro de cambiar el estado a {status}?',
    'dash.confirm_btn': 'Confirmar Cambio',
    'dash.reviews': 'Reseñas',
    'dash.reviews_title': 'Gestión de Reseñas',
    'dash.reply': 'Responder',
    'dash.delete_review': 'Eliminar Reseña',
    'dash.reply_placeholder': 'Escribe tu respuesta pública...',
    'dash.reply_save': 'Publicar Respuesta',
    'dash.replied': 'Respondida',


    // Reviews
    'reviews.title': 'Reseñas de Clientes',
    'reviews.write': 'Escribir Reseña',
    'reviews.rating': 'Calificación',
    'reviews.submit': 'Enviar Reseña',
    'reviews.login_to_write': 'Inicia sesión para escribir una reseña',
    'reviews.no_reviews': 'Aún no hay reseñas. ¡Sé el primero en opinar!',
    'reviews.success': '¡Reseña enviada con éxito!',
    'reviews.comment_placeholder': 'Comparte tu experiencia con este producto...',
    'reviews.based_on': 'Basado en {0} reseñas',
    'reviews.delete': 'Eliminar',
    'reviews.already_reviewed': 'Ya calificaste este producto',
    'reviews.delivered_only': 'Recibe el pedido para calificar',
    'reviews.rate_btn': 'Calificar Producto',

    // Profile & Addresses
    'profile.title': 'Mi Perfil',
    'profile.personal': 'Información Personal',
    'profile.addresses': 'Mis Direcciones',
    'profile.security': 'Seguridad',
    'profile.save': 'Guardar Cambios',
    'profile.update_success': 'Perfil actualizado con éxito',
    'profile.password_title': 'Cambiar Contraseña',
    'profile.new_password': 'Nueva Contraseña',
    'profile.confirm_password': 'Confirmar Contraseña',
    'profile.password_success': 'Contraseña actualizada',
    
    'address.add': 'Agregar Dirección',
    'address.edit': 'Editar',
    'address.delete': 'Eliminar',
    'address.default': 'Predeterminada',
    'address.set_default': 'Establecer como PD',
    'address.name': 'Nombre (ej. Casa)',
    'address.recipient': 'Destinatario',
    'address.street': 'Dirección',
    'address.city': 'Ciudad',
    'address.phone': 'Celular',
    'address.save': 'Guardar Dirección',
    'address.no_addresses': 'No tienes direcciones guardadas',


    // My Orders
    'my_orders.title': 'Mis Pedidos',
    'my_orders.desc': 'Rastrea y administra tus compras recientes',
    'my_orders.no_orders': 'Aún no hay pedidos',
    'my_orders.no_orders_desc': 'Parece que no has comprado nada aún.',
    'my_orders.start_shopping': 'Empezar a Comprar',
    'my_orders.total': 'Total',
    'dash.custom': 'Personalizado',
    'dash.no_data_export': 'No hay datos para exportar',
    
    // New additions
    'filters.price_title': 'Precio',
    'filters.size_title': 'Talla',
    'filters.min_placeholder': 'Min',
    'filters.max_placeholder': 'Max',
    'filters.apply': 'Aplicar',
    'cat.caps': 'Gorras',
    'cat.jackets': 'Chaquetas',
    'dash.clear_colors': 'Limpiar Todos',
    'product.promo': 'PROMO',
    'promos.upto_off': 'Hasta {0}% OFF',
    'dash.gender_unisex': 'Unisex',
    'dash.gender_men': 'Hombres',
    'dash.gender_women': 'Mujeres',
    
    // Payment Result Pages
    'page.pending.title': 'Pago Pendiente',
    'page.pending.desc': 'Tu pago se está procesando. Te notificaremos cuando se confirme.',
    'page.pending.check_status': 'Ver Estado del Pedido',
    'page.pending.back_home': 'Volver al Inicio',
    'page.success.title': '¡Pago Exitoso!',
    'page.success.desc': 'Gracias por tu compra. Tu pedido ha sido confirmado.',
    'page.success.view_order': 'Ver Mi Pedido',
    'page.success.continue_shopping': 'Seguir Comprando',
    'page.failure.title': 'Pago Fallido',
    'page.failure.desc': 'Hubo un problema al procesar tu pago. Por favor intenta nuevamente.',
    'page.failure.try_again': 'Intentar Nuevamente',
    'page.failure.contact_support': 'Contactar Soporte',

    // Dashboard Filters
    'dash.all_categories': 'Todas las Categorías',
    'dash.all_sizes': 'Todas las Tallas',
    'dash.filter_stock_all': 'Todo el Inventario',
    'dash.filter_in_stock': 'En Stock',
    'dash.filter_low_stock': 'Pocas Unidades',
    'dash.filter_out_of_stock': 'Agotado',
    'dash.filter_min_price': 'Precio Min',
    'dash.filter_max_price': 'Precio Max',
    'dash.na': 'N/A',

  },
  en: {
    'auth.logout_confirm.title': 'Sign Out?',
    'auth.logout_confirm.description': 'Are you sure you want to sign out? You will need to sign in again to access your account.',
    'auth.logout_confirm.cancel': 'Cancel',
    'auth.logout_confirm.confirm': 'Sign Out',
    'nav.login': 'Login',
    'nav.cart': 'Cart',
    'nav.home': 'Home',
    'nav.shop': 'Shop',
    'nav.discounts': 'Discounts',
    'hero.title': 'Future of Fashion',
    'hero.subtitle': 'Curated collection of dystopian streetwear and cyberpunk aesthetics.',
    'product.new': 'NEW',
    'products.add': 'Add',
    'auth.welcome': 'Welcome to ThunderXis',
    'auth.subtitle': 'Enter your credentials to access',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.login': 'Sign In',
    'auth.register': 'Sign Up',
    'auth.no_account': 'Don\'t have an account?',
    'auth.create': 'Create account',
    'auth.name': 'Full Name',
    'auth.premium': 'Premium Quality',
    'auth.premium.desc': 'Selected materials for durability and comfort.',
    'auth.style': 'Urban Style',
    'auth.style.desc': 'Exclusive designs that define trends.',
    'auth.join.desc': 'Join the most exclusive fashion community.',
    'auth.have_account': 'Already have an account?',
    'auth.logout': 'Logout',
    'cart.empty': 'Your cart is empty.',
    'cart.size': 'Size',
    'cart.login_required': 'Please login to complete your order.',
    'checkout.secure_payment': 'Secure payments via Mercado Pago',
    'product.not_found': 'Product Not Found',
    'product.select_size': 'Select Size',
    'product.shipping_info': 'Free shipping on orders over $200,000',
    'product.return_policy': '30-day return policy',
    'nav.account': 'Account',
    'nav.orders': 'My Orders',
    'nav.favorites': 'Favorites',
    'nav.menu': 'Menu',
    'nav.language': 'Language',
    'favorites.login_msg': 'Please login to view your favorites.',
    'favorites.empty': 'No saved items yet.',
    'favorites.browse': 'Browse Shop',
    'favorites.added': 'Added to favorites',
    'favorites.removed': 'Removed from favorites',
    'favorites.error_add': 'Error adding to favorites',
    'favorites.error_remove': 'Error removing from favorites',
    'favorites.login_required': 'Please login to save favorites',
    'checkout.redirecting': 'Redirecting to Payment...',
    'checkout.init_failed': 'Payment initialization failed',
    'checkout.missing_fields': 'Missing shipping fields',
    'cart.added_success': 'Added to cart',
    'footer.address': 'Bogotá, Colombia',
    // New
    'home.new_arrivals': 'New Arrivals',
    'home.new_drops': 'New Drops',
    'home.view_all': 'View All',
    'filters.title': 'Filters',
    'filters.gender': 'Gender',
    'filters.men': 'Men',
    'filters.women': 'Women',
    'filters.categories': 'Categories',
    'cat.hoodies': 'Hoodies',
    'cat.tshirts': 'T-Shirts',
    'cat.pants': 'Pants',
    'cat.footwear': 'Footwear',
    'cat.accessories': 'Accessories',
    'hero.cta': 'Shop Collection',
    // Footer
    'footer.about': 'About Us',
    'footer.description': 'Redefining streetwear with futuristic aesthetics and premium materials.',
    'footer.shop': 'Shop',
    'footer.help': 'Help',
    'footer.legal': 'Legal',
    'footer.links.men': 'Men',
    'footer.links.women': 'Women',
    'footer.links.sale': 'Sale',
    'footer.help.shipping': 'Shipping',
    'footer.help.returns': 'Returns',
    'footer.help.contact': 'Contact',
    'footer.newsletter': 'Subscribe',
    'footer.newsletter.desc': 'Get the latest drops and exclusive offers.',
    'footer.rights': 'All rights reserved.',
    // WhatsApp
    'whatsapp.chat': 'Chat with us',
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.shipping': 'Shipping Information',
    'checkout.name': 'Full Name',
    'checkout.address': 'Shipping Address',
    'checkout.city': 'City',
    'checkout.phone': 'Phone Number',
    'checkout.placeholder_name': 'Eg: John Doe',
    'checkout.placeholder_address': 'Eg: 123 Main St',
    'checkout.placeholder_phone': 'Eg: 555-0123',
    'checkout.summary': 'Order Summary',
    'checkout.subtotal': 'Subtotal',
    'checkout.shipping_cost': 'Shipping Cost',
    'checkout.total': 'Total',
    'checkout.pay': 'Pay with Mercado Pago',
    'checkout.processing': 'Processing...',
    'checkout.error': 'Error processing order',
    'checkout.select_city': 'Select your city',
    'checkout.select_city_calc': 'Select your city to calculate shipping',
    'filters.banner.title': 'Winter Sale',
    'filters.banner.desc': 'Get up to 50% off on selected items.',
    'filters.banner.cta': 'View Offers',
    'nav.dashboard': 'Dashboard',
    'products.details': 'View Details',
    'product.quantity': 'Quantity',
    'product.size_guide': 'Size Guide',
    'product.available_stock': 'units available',
    'product.out_of_stock': 'Out of Stock',
    'discounts.limited_time': 'Limited Time',
    'discounts.no_active': 'No active offers',
    'discounts.updating_inventory': 'We are updating our inventory. Check back soon.',
    'discounts.back_to_shop': 'Back to Shop',
    'shop.no_results': 'No products found matching these filters.',
    'shop.clear_filters': 'Clear Filters',
    'nav.orders_tooltip': 'Login to view orders',
    'footer.subscribe_btn': 'Subscribe',
    'dash.create_product': 'Create Product',
    'dash.name': 'Product Name',
    'dash.price': 'Price',
    'dash.desc': 'Description',
    'dash.rating': 'Rating',
    'dash.img': 'Image URL',
    'dash.cat': 'Category',
    'dash.gender': 'Gender',
    'dash.stock': 'Stock',
    'dash.create_btn': 'Publish Product',
    'dash.success': 'Product created successfully',
    'dash.users': 'Users',
    'dash.products': 'Products',
    'dash.analytics': 'Analytics',
    'dash.orders': 'Orders',
    // Dashboard comprehensive translations
    'dash.user_management': 'User Management',
    'dash.user_desc': 'Manage user roles and permissions',
    'dash.search': 'Search',
    'dash.total_users': 'Total Users',
    'dash.owners': 'Owners',
    'dash.regular_users': 'Regular Users',
    'dash.role': 'Role',
    'dash.joined': 'Joined',
    'dash.actions': 'Actions',
    'dash.delete_user': 'Delete user',
    'dash.click_toggle': 'Click to toggle',
    'dash.no_users': 'No users found',
    'dash.warning_zone': 'Sensitive administration zone',
    'dash.role_warning': 'Only change roles for trusted users. Owner role has full dashboard access.',
    // Orders
    'dash.orders_management': 'Orders Management',
    'dash.orders_desc': 'Manage shipping and order fulfillment',
    'dash.total_orders': 'Total Orders',
    'dash.all': 'All',
    'dash.pending': 'Pending',
    'dash.paid': 'Paid',
    'dash.shipped': 'Shipped',
    'dash.delivered': 'Delivered',
    'dash.cancelled': 'Cancelled',
    'dash.customer': 'Customer',
    'dash.date': 'Date',
    'dash.amount': 'Amount',
    'dash.status': 'Status',
    'dash.phone': 'Phone',
    'dash.city': 'City',
    'dash.address': 'Address',
    'dash.mark_paid': 'Mark as Paid',
    'dash.ship_order': 'Ship Order',
    'dash.mark_delivered': 'Mark Delivered',
    'dash.no_orders': 'No orders yet',
    // Products
    'dash.add_product': 'Add Product',
    'dash.product_management': 'Product Management',
    'dash.manage_inventory': 'Manage your store inventory',
    'dash.search_products': 'Search products...',
    'dash.product_name': 'Product Name',
    'dash.category': 'Category',
    'dash.new_product': 'New Product',
    'dash.edit_product': 'Edit Product',
    'dash.product_details': 'Fill in the product details',
    'dash.basic_info': 'Basic Information',
    'dash.select_category': 'Select category',
    'dash.available_sizes': 'Available Sizes',
    'dash.colors': 'Colors',
    'dash.click_add_colors': 'Click to add colors',
    'dash.product_images': 'Product Images',
    'dash.click_upload': 'Click to upload images',
    'dash.upload_limit': 'PNG, JPG up to 5MB',
    'dash.mark_new': 'Mark as NEW product',
    'dash.cancel': 'Cancel',
    'dash.save_product': 'Save Product',
    'dash.uploading': 'Uploading...',
    'dash.no_products': 'No products found',
    'dash.add_first': 'Add your first product!',
    'dash.delete_confirm': 'Are you sure you want to delete this product?',
    'dash.sale_price_label': 'Sale Price (Optional)',
    'dash.sale_price_placeholder': 'Sale price...',
    'dash.filter_rating': 'Min Rating',
    'dash.rating_label': 'Initial Rating (Static)',
    'dash.rating_help': 'Default stars to display',

    'dash.error_save_product': 'Error saving product',
    'dash.error_delete_product': 'Error deleting product',
    // Navbar
    'dash.notifications': 'Notifications',
    'dash.language': 'Language',
    'dash.profile': 'Profile',
    'dash.settings': 'Settings',
    'dash.administrator': 'Administrator',
    'dash.export': 'Export',
    'dash.export_csv': 'Export CSV',
    'dash.daily': 'Daily',
    'dash.weekly': 'Weekly',
    'dash.monthly': 'Monthly',
    'dash.monitor_performance': 'Monitor your business performance',
    'dash.revenue': 'Revenue',
    'dash.revenue_trend': 'Revenue Trend',
    'dash.orders_volume': 'Orders Volume',
    'dash.recent_orders': 'Recent Orders',
    'dash.view_all': 'View All',
    'dash.total_sales': 'Total Sales',
    'dash.customers': 'Customers',
    'dash.avg_order': 'Avg Order',
    'dash.order_id': 'Order ID',
    // Additional Dashboard Translations
    'dash.access_denied': 'Access Denied',
    'dash.no_permission': 'You do not have permission to view this page.',
    'dash.user_label': 'User:',
    'dash.role_label': 'Role:',
    'dash.required_role': 'Required Role:',
    'dash.go_home': 'Go Home',
    'dash.admin': 'Admin',
    'dash.panel': 'Dashboard Panel',
    'dash.no_data': 'No data',
    'dash.search_placeholder': 'Search...',
    'dash.user': 'User',
    'dash.search_users': 'Search users...',
    'dash.no_users_search': 'No users found matching your search',
    'dash.role_change_confirm': 'Are you sure you want to change this user to {role}?',
    'dash.error_role_change': 'Error changing role',
    'dash.delete_confirm_user': '⚠️ Are you SURE you want to delete {email}\'s account?\n\nThis action CANNOT be UNDONE.',
    'dash.error_delete_user': 'Error deleting user',
    'dash.search_orders': 'Search by ID or customer...',
    'dash.no_orders_search': 'No orders found matching your search',
    'dash.customer_label': 'Customer:',
    'dash.date_label': 'Date:',
    'dash.phone_label': 'Phone:',
    'dash.city_label': 'City:',
    'dash.address_label': 'Address:',
    'dash.error_update_order': 'Error updating order status',
    'dash.owner': 'Owner',
    'dash.confirm_status_title': 'Confirm Change',
    'dash.confirm_status_desc': 'Are you sure you want to change status to {status}?',
    'dash.confirm_btn': 'Confirm Change',
    'dash.reviews': 'Reviews',
    'dash.reviews_title': 'Reviews Management',
    'dash.reply': 'Reply',
    'dash.delete_review': 'Delete Review',
    'dash.reply_placeholder': 'Write your public reply...',
    'dash.reply_save': 'Post Reply',
    'dash.replied': 'Replied',


    // Reviews
    'reviews.title': 'Customer Reviews',
    'reviews.write': 'Write a Review',
    'reviews.rating': 'Rating',
    'reviews.submit': 'Submit Review',
    'reviews.login_to_write': 'Login to write a review',
    'reviews.no_reviews': 'No reviews yet. Be the first to review!',
    'reviews.success': 'Review submitted successfully!',
    'reviews.comment_placeholder': 'Share your experience with this product...',
    'reviews.based_on': 'Based on {0} reviews',
    'reviews.delete': 'Delete',
    'reviews.already_reviewed': 'You already reviewed this product',
    'reviews.delivered_only': 'Receive order to rate',
    'reviews.rate_btn': 'Rate Product',

    // Profile & Addresses
    'profile.title': 'My Profile',
    'profile.personal': 'Personal Information',
    'profile.addresses': 'My Addresses',
    'profile.security': 'Security',
    'profile.save': 'Save Changes',
    'profile.update_success': 'Profile updated successfully',
    'profile.password_title': 'Change Password',
    'profile.new_password': 'New Password',
    'profile.confirm_password': 'Confirm Password',
    'profile.password_success': 'Password updated successfully',

    'address.add': 'Add New Address',
    'address.edit': 'Edit',
    'address.delete': 'Delete',
    'address.default': 'Default',
    'address.set_default': 'Set as Default',
    'address.name': 'Label (e.g. Home)',
    'address.recipient': 'Recipient Name',
    'address.street': 'Street Address',
    'address.city': 'City',
    'address.phone': 'Phone',
    'address.save': 'Save Address',
    'address.no_addresses': 'No addresses saved',


    // My Orders
    'my_orders.title': 'My Orders',
    'my_orders.desc': 'Track and manage your recent purchases',
    'my_orders.no_orders': 'No orders yet',
    'my_orders.no_orders_desc': 'Looks like you haven\'t bought anything yet.',
    'my_orders.start_shopping': 'Start Shopping',
    'my_orders.total': 'Total',
    'dash.custom': 'Custom',
    'dash.no_data_export': 'No data to export',

    // New additions
    'filters.price_title': 'Price',
    'filters.size_title': 'Size',
    'filters.min_placeholder': 'Min',
    'filters.max_placeholder': 'Max',
    'filters.apply': 'Apply',
    'cat.caps': 'Caps',
    'cat.jackets': 'Jackets',
    'dash.clear_colors': 'Clear All',
    'product.promo': 'PROMO',
    'promos.upto_off': 'Up to {0}% OFF',
    'dash.gender_unisex': 'Unisex',
    'dash.gender_men': 'Men',
    'dash.gender_women': 'Women',

    // Payment Result Pages
    'page.pending.title': 'Payment Pending',
    'page.pending.desc': 'Your payment is being processed. We will notify you once confirmed.',
    'page.pending.check_status': 'Check Order Status',
    'page.pending.back_home': 'Back to Home',
    'page.success.title': 'Payment Successful!',
    'page.success.desc': 'Thank you for your purchase. Your order has been confirmed.',
    'page.success.view_order': 'View My Order',
    'page.success.continue_shopping': 'Continue Shopping',
    'page.failure.title': 'Payment Failed',
    'page.failure.desc': 'There was an issue processing your payment. Please try again.',
    'page.failure.try_again': 'Try Again',
    'page.failure.contact_support': 'Contact Support',

    // Dashboard Filters
    'dash.all_categories': 'All Categories',
    'dash.all_sizes': 'All Sizes',
    'dash.filter_stock_all': 'All Inventory',
    'dash.filter_in_stock': 'In Stock',
    'dash.filter_low_stock': 'Low Stock',
    'dash.filter_out_of_stock': 'Out of Stock',
    'dash.filter_min_price': 'Min Price',
    'dash.filter_max_price': 'Max Price',
    'dash.na': 'N/A',

  },
  fr: {
    'auth.logout_confirm.title': 'Se Déconnecter ?',
    'auth.logout_confirm.description': 'Êtes-vous sûr de vouloir vous déconnecter ? Vous devrez vous reconnecter pour accéder à votre compte.',
    'auth.logout_confirm.confirm': 'Se Déconnecter',
    'nav.login': 'Connexion',
    'nav.cart': 'Panier',
    'nav.home': 'Accueil',
    'nav.shop': 'Boutique',
    'nav.discounts': 'Promotions',
    'hero.title': 'L\'Avenir de la Mode',
    'hero.subtitle': 'Collection curatée de streetwear dystopique.',
    'product.new': 'NOUVEAU',
    'products.add': 'Ajouter',
    'auth.welcome': 'Bienvenue chez ThunderXis',
    'auth.subtitle': 'Entrez vos identifiants',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.login': 'Se connecter',
    'auth.register': 'S\'inscrire',
    'auth.no_account': 'Pas de compte ?',
    'auth.create': 'Créer un compte',
    'auth.name': 'Nom complet',
    'auth.premium': 'Qualité Premium',
    'auth.premium.desc': 'Matériaux sélectionnés pour la durabilité.',
    'auth.style': 'Style Urbain',
    'auth.style.desc': 'Designs exclusifs qui définissent les tendances.',
    'auth.join.desc': 'Rejoignez la communauté de mode la plus exclusive.',
    'auth.have_account': 'Vous avez déjà un compte ?',
    'auth.logout': 'Déconnexion',
    'cart.empty': 'Votre panier est vide.',
    'cart.size': 'Taille',
    'cart.login_required': 'Veuillez vous connecter pour commander.',
    'checkout.secure_payment': 'Paiement sécurisé via Mercado Pago',
    'product.not_found': 'Produit non trouvé',
    'product.select_size': 'Choisir Taille',
    'product.shipping_info': 'Livraison gratuite > $200.000',
    'product.return_policy': 'Politique de retour 30 jours',
    'nav.account': 'Compte',
    'nav.orders': 'Mes Commandes',
    'nav.favorites': 'Favoris',
    'nav.menu': 'Menu',
    'nav.language': 'Langue',
    'favorites.login_msg': 'Connectez-vous pour voir vos favoris.',
    'favorites.empty': 'Aucun favori pour le moment.',
    'favorites.browse': 'Explorer la Boutique',
    'favorites.added': 'Ajouté aux favoris',
    'favorites.removed': 'Retiré des favoris',
    'favorites.error_add': 'Erreur lors de l\'ajout',
    'favorites.error_remove': 'Erreur lors de la suppression',
    'favorites.login_required': 'Connectez-vous pour sauvegarder',
    'checkout.redirecting': 'Redirection vers le paiement...',
    'checkout.init_failed': 'Échec de l\'initialisation du paiement',
    'checkout.missing_fields': 'Champs de livraison manquants',
    'cart.added_success': 'Ajouté au panier',
    'footer.address': 'Bogotá, Colombie',
    // New
    'home.new_arrivals': 'Nouveautés',
    'home.new_drops': 'Nouveautés',
    'home.view_all': 'Tout Voir',
    'filters.title': 'Filtres',
    'filters.gender': 'Genre',
    'filters.men': 'Hommes',
    'filters.women': 'Femmes',
    'filters.categories': 'Catégories',
    'cat.hoodies': 'Sweats',
    'cat.tshirts': 'T-Shirts',
    'cat.pants': 'Pantalons',
    'cat.footwear': 'Chaussures',
    'cat.accessories': 'Accessoires',
    'hero.cta': 'Voir la Collection',
    // Footer
    'footer.about': 'À Propos',
    'footer.description': 'Redéfinir le streetwear avec une esthétique futuriste.',
    'footer.shop': 'Boutique',
    'footer.help': 'Aide',
    'footer.legal': 'Légal',
    'footer.links.men': 'Hommes',
    'footer.links.women': 'Femmes',
    'footer.links.sale': 'Soldes',
    'footer.help.shipping': 'Livraison',
    'footer.help.returns': 'Retours',
    'dash.filter_rating': 'Note Min',
    'dash.rating_label': 'Note Initiale (Fixe)',
    'dash.rating_help': 'Étoiles à afficher par défaut',

    'footer.help.contact': 'Contact',
    'footer.newsletter': 'S\'abonner',
    'footer.newsletter.desc': 'Recevez les dernières nouveautés.',
    'footer.rights': 'Tous droits réservés.',
    // WhatsApp
    'whatsapp.chat': 'Discutez avec nous',
    // Checkout
    'checkout.title': 'Caisse',
    'checkout.shipping': 'Livraison',
    'checkout.name': 'Nom complet',
    'checkout.address': 'Adresse',
    'checkout.city': 'Ville',
    'checkout.phone': 'Téléphone',
    'checkout.placeholder_name': 'Ex: Jean Dupont',
    'checkout.placeholder_address': 'Ex: 12 rue de la Paix',
    'checkout.placeholder_phone': 'Ex: 06 12 34 56 78',
    'checkout.summary': 'Résumé',
    'checkout.subtotal': 'Sous-total',
    'checkout.shipping_cost': 'Frais de port',
    'checkout.total': 'Total',
    'checkout.pay': 'Payer avec Mercado Pago',
    'checkout.processing': 'Traitement...',
    'checkout.error': 'Erreur de traitement',
    'checkout.select_city': 'Sélectionnez votre ville',
    'checkout.select_city_calc': 'Sélectionnez votre ville pour calculer les frais de port',
    'filters.banner.title': 'Soldes d\'Hiver',
    'filters.banner.desc': 'Jusqu\'à 50% de réduction.',
    'filters.banner.cta': 'Voir Offres',
    'nav.dashboard': 'Dashboard',
    'products.details': 'Voir Détails',
    'product.quantity': 'Quantité',
    'product.size_guide': 'Guide des tailles',
    'product.available_stock': 'unités disponibles',
    'product.out_of_stock': 'Rupture de stock',
    'discounts.limited_time': 'Temps Limité',
    'discounts.no_active': 'Pas d\'offres actives',
    'discounts.updating_inventory': 'Nous mettons à jour notre inventaire. Revenez bientôt.',
    'discounts.back_to_shop': 'Retour à la Boutique',
    'shop.no_results': 'Aucun produit trouvé avec ces filtres.',
    'shop.clear_filters': 'Effacer les filtres',
    'nav.orders_tooltip': 'Connectez-vous pour voir les commandes',
    'footer.subscribe_btn': 'S\'abonner',
    'dash.create_product': 'Créer Produit',
    'dash.name': 'Nom du Produit',
    'dash.price': 'Prix',
    'dash.desc': 'Description',
    'dash.img': 'URL de l\'image',
    'dash.cat': 'Catégorie',
    'dash.gender': 'Genre',
    'dash.stock': 'Stock',
    'dash.create_btn': 'Publier Produit',
    'dash.success': 'Produit créé avec succès',
    'dash.users': 'Utilisateurs',
    'dash.products': 'Produits',
    'dash.analytics': 'Analytique',
    'dash.orders': 'Commandes',
    // Dashboard comprehensive translations
    'dash.user_management': 'Gestion des Utilisateurs',
    'dash.user_desc': 'Gérer les rôles et permissions',
    'dash.search': 'Rechercher',
    'dash.total_users': 'Total Utilisateurs',
    'dash.owners': 'Propriétaires',
    'dash.regular_users': 'Utilisateurs Réguliers',
    'dash.role': 'Rôle',
    'dash.joined': 'Inscrit',
    'dash.actions': 'Actions',
    'dash.delete_user': 'Supprimer utilisateur',
    'dash.click_toggle': 'Cliquer pour changer',
    'dash.no_users': 'Aucun utilisateur trouvé',
    'dash.warning_zone': 'Zone d\'administration sensible',
    'dash.role_warning': 'Ne changez les rôles que pour les utilisateurs de confiance. Le rôle Owner a un accès complet.',
    'dash.orders_management': 'Gestion des Commandes',
    'dash.orders_desc': 'Gérer l\'expédition et les commandes',
    'dash.all': 'Tous',
    'dash.pending': 'En attente',
    'dash.paid': 'Payé',
    'dash.shipped': 'Expédié',
    'dash.delivered': 'Livré',
    'dash.cancelled': 'Annulé',
    'dash.customer': 'Client',
    'dash.date': 'Date',
    'dash.amount': 'Montant',
    'dash.status': 'Statut',
    'dash.phone': 'Téléphone',
    'dash.city': 'Ville',
    'dash.address': 'Adresse',
    'dash.mark_paid': 'Marquer comme payé',
    'dash.ship_order': 'Expédier',
    'dash.mark_delivered': 'Marquer livré',
    'dash.no_orders': 'Pas encore de commandes',
    'dash.add_product': 'Ajouter Produit',
    'dash.product_management': 'Gestion des Produits',
    'dash.manage_inventory': 'Gérer l\'inventaire',
    'dash.search_products': 'Rechercher produits...',
    'dash.product_name': 'Nom du Produit',
    'dash.category': 'Catégorie',
    'dash.new_product': 'Nouveau Produit',
    'dash.edit_product': 'Modifier Produit',
    'dash.product_details': 'Détails du produit',
    'dash.basic_info': 'Informations de Base',
    'dash.select_category': 'Sélectionner catégorie',
    'dash.available_sizes': 'Tailles Disponibles',
    'dash.colors': 'Couleurs',
    'dash.click_add_colors': 'Cliquer pour ajouter des couleurs',
    'dash.product_images': 'Imágenes du Produit',
    'dash.click_upload': 'Cliquer pour télécharger',
    'dash.upload_limit': 'PNG, JPG jusqu\'à 5MB',
    'dash.mark_new': 'Marquer comme NOUVEAU',
    'dash.cancel': 'Annuler',
    'dash.save_product': 'Enregistrer Produit',
    'dash.uploading': 'Téléchargement...',
    'dash.no_products': 'Aucun produit trouvé',
    'dash.add_first': 'Ajoutez votre premier produit!',
    'dash.delete_confirm': 'Êtes-vous sûr de supprimer ce produit?',
    'dash.sale_price_label': 'Prix Soldé (Optionnel)',
    'dash.sale_price_placeholder': 'Prix soldé...',
    'dash.error_save_product': 'Erreur lors de l\'enregistrement',
    'dash.error_delete_product': 'Erreur lors de la suppression',
    'dash.notifications': 'Notifications',
    'dash.language': 'Langue',
    'dash.profile': 'Profil',
    'dash.settings': 'Paramètres',
    'dash.administrator': 'Administrateur',
    'dash.export': 'Exporter',
    'dash.export_csv': 'Exporter CSV',
    'dash.daily': 'Quotidien',
    'dash.weekly': 'Hebdomadaire',
    'dash.monthly': 'Mensuel',
    'dash.monitor_performance': 'Surveillez les performances',
    'dash.revenue': 'Revenus',
    'dash.revenue_trend': 'Tendance des Revenus',
    'dash.orders_volume': 'Volume de Commandes',
    'dash.recent_orders': 'Commandes Récentes',
    'dash.view_all': 'Voir Tout',
    'dash.total_sales': 'Ventes Totales',
    'dash.total_orders': 'Total Commandes',
    'dash.customers': 'Clients',
    'dash.avg_order': 'Commande Moyenne',
    'dash.order_id': 'ID Commande',
    // Additional Dashboard Translations
    'dash.access_denied': 'Accès Refusé',
    'dash.no_permission': 'Vous n\'avez pas la permission de voir cette page.',
    'dash.user_label': 'Utilisateur:',
    'dash.role_label': 'Rôle:',
    'dash.required_role': 'Rôle Requis:',
    'dash.go_home': 'Retour à l\'Accueil',
    'dash.admin': 'Admin',
    'dash.panel': 'Panneau de Dashboard',
    'dash.no_data': 'Pas de données',
    'dash.search_placeholder': 'Rechercher...',
    'dash.user': 'Utilisateur',
    'dash.search_users': 'Rechercher des utilisateurs...',
    'dash.no_users_search': 'Aucun utilisateur trouvé correspondant à votre recherche',
    'dash.role_change_confirm': 'Êtes-vous sûr de vouloir changer cet utilisateur en {role}?',
    'dash.error_role_change': 'Erreur lors du changement de rôle',
    'dash.delete_confirm_user': '⚠️ Êtes-vous SÛR de vouloir supprimer le compte de {email}?\n\nCette action NE PEUT PAS être ANNULÉE.',
    'dash.error_delete_user': 'Erreur lors de la suppression de l\'utilisateur',
    'dash.search_orders': 'Rechercher par ID ou client...',
    'dash.no_orders_search': 'Aucune commande trouvée correspondant à votre recherche',
    'dash.customer_label': 'Client:',
    'dash.date_label': 'Date:',
    'dash.phone_label': 'Téléphone:',
    'dash.city_label': 'Ville:',
    'dash.address_label': 'Adresse:',
    'dash.error_update_order': 'Erreur lors de la mise à jour du statut de la commande',
    'dash.owner': 'Propriétaire',
    'dash.confirm_status_title': 'Confirmer Changement',
    'dash.confirm_status_desc': 'Êtes-vous sûr de vouloir changer le statut en {status} ?',
    'dash.confirm_btn': 'Confirmer',
    'dash.reviews': 'Avis',
    'dash.reviews_title': 'Gestion des Avis',
    'dash.reply': 'Répondre',
    'dash.delete_review': 'Supprimer l\'avis',
    'dash.reply_placeholder': 'Écrivez votre réponse publique...',
    'dash.reply_save': 'Publier la réponse',
    'dash.replied': 'Répondu',


    // Reviews
    'reviews.title': 'Avis Clients',
    'reviews.write': 'Écrire un avis',
    'reviews.rating': 'Note',
    'reviews.submit': 'Envoyer',
    'reviews.login_to_write': 'Connectez-vous pour écrire un avis',
    'reviews.no_reviews': 'Pas encore d\'avis. Soyez le premier !',
    'reviews.success': 'Avis envoyé avec succès !',
    'reviews.comment_placeholder': 'Partagez votre expérience...',
    'reviews.based_on': 'Basé sur {0} avis',
    'reviews.delete': 'Supprimer',
    'reviews.already_reviewed': 'Vous avez déjà noté ce produit',
    'reviews.delivered_only': 'Recevoir la commande pour noter',
    'reviews.rate_btn': 'Noter le Produit',

    // Profile & Addresses
    'profile.title': 'Mon Profil',
    'profile.personal': 'Informations Personnelles',
    'profile.addresses': 'Mes Adresses',
    'profile.security': 'Sécurité',
    'profile.save': 'Enregistrer',
    'profile.update_success': 'Profil mis à jour',
    'profile.password_title': 'Changer le mot de passe',
    'profile.new_password': 'Nouveau mot de passe',
    'profile.confirm_password': 'Confirmer le mot de passe',
    'profile.password_success': 'Mot de passe mis à jour',

    'address.add': 'Ajouter une adresse',
    'address.edit': 'Modifier',
    'address.delete': 'Supprimer',
    'address.default': 'Par défaut',
    'address.set_default': 'Définir par défaut',
    'address.name': 'Nom (ex. Maison)',
    'address.recipient': 'Destinataire',
    'address.street': 'Adresse',
    'address.city': 'Ville',
    'address.phone': 'Téléphone',
    'address.save': 'Enregistrer l\'adresse',
    'address.no_addresses': 'Aucune adresse enregistrée',


    // My Orders
    'my_orders.title': 'Mes Commandes',
    'my_orders.desc': 'Suivez et gérez vos achats récents',
    'my_orders.no_orders': 'Pas encore de commandes',
    'my_orders.no_orders_desc': 'Il semble que vous n\'ayez rien acheté encore.',
    'my_orders.start_shopping': 'Commencer vos achats',
    'my_orders.total': 'Total',
    'dash.custom': 'Personnalisé',
    'dash.no_data_export': 'Pas de données à exporter',

    // New additions
    'filters.price_title': 'Prix',
    'filters.size_title': 'Taille',
    'filters.min_placeholder': 'Min',
    'filters.max_placeholder': 'Max',
    'filters.apply': 'Appliquer',
    'cat.caps': 'Casquettes',
    'cat.jackets': 'Vestes',
    'dash.clear_colors': 'Tout effacer',
    'product.promo': 'PROMO',
    'promos.upto_off': 'Jusqu\'à {0}%',
    'dash.gender_unisex': 'Unisexe',
    'dash.gender_men': 'Hommes',
    'dash.gender_women': 'Femmes',

    // Payment Result Pages
    'page.pending.title': 'Paiement en Attente',
    'page.pending.desc': 'Votre paiement est en cours de traitement. Nous vous informerons une fois confirmé.',
    'page.pending.check_status': 'Voir Statut de la Commande',
    'page.pending.back_home': 'Retour à l\'Accueil',
    'page.success.title': 'Paiement Réussi !',
    'page.success.desc': 'Merci pour votre achat. Votre commande a été confirmée.',
    'page.success.view_order': 'Voir Ma Commande',
    'page.success.continue_shopping': 'Continuer vos Achats',
    'page.failure.title': 'Échec du Paiement',
    'page.failure.desc': 'Un problème est survenu lors du traitement de votre paiement. Veuillez réessayer.',
    'page.failure.try_again': 'Réessayer',
    'page.failure.contact_support': 'Contacter le Support',

    // Dashboard Filters
    'dash.all_categories': 'Toutes les Catégories',
    'dash.all_sizes': 'Toutes les Tailles',
    'dash.filter_stock_all': 'Tout l\'Inventaire',
    'dash.filter_in_stock': 'En Stock',
    'dash.filter_low_stock': 'Stock Faible',
    'dash.filter_out_of_stock': 'Épuisé',
    'dash.filter_min_price': 'Prix Min',
    'dash.filter_max_price': 'Prix Max',
    'dash.na': 'N/A',

  },
  pt: {
    'auth.logout_confirm.title': 'Sair?',
    'auth.logout_confirm.description': 'Tem certeza que deseja sair? Você precisará fazer login novamente para acessar sua conta.',
    'auth.logout_confirm.cancel': 'Cancelar',
    'auth.logout_confirm.confirm': 'Sair',
    'nav.login': 'Entrar',
    'nav.cart': 'Carrinho',
    'nav.home': 'Início',
    'nav.shop': 'Loja',
    'nav.discounts': 'Descontos',
    'nav.language': 'Idioma',
    'hero.title': 'O Futuro da Moda',
    'hero.subtitle': 'Coleção curada de streetwear distópico.',
    'checkout.select_city_calc': 'Selecione sua cidade para calcular o frete',
    'home.new_arrivals': 'Novos Lançamentos', // Assuming this key lines up with PT section approximately
    'home.new_drops': 'Novos',
    'products.add': 'Adicionar',
    'auth.welcome': 'Bem-vindo à ThunderXis',
    'auth.subtitle': 'Insira suas credenciais',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.login': 'Entrar',
    'auth.register': 'Registrar',
    'auth.no_account': 'Não tem conta?',
    'auth.create': 'Criar conta',
    'auth.name': 'Nome Completo',
    'auth.premium': 'Qualidade Premium',
    'auth.premium.desc': 'Materiais selecionados para durabilidade.',
    'auth.style': 'Estilo Urbano',
    'auth.style.desc': 'Designs exclusivos que definem tendências.',
    'auth.join.desc': 'Junte-se à comunidade de moda mais exclusiva.',
    'auth.have_account': 'Já tem uma conta?',
    'auth.logout': 'Sair',
    'cart.empty': 'Seu carrinho está vazio.',
    'cart.size': 'Tamanho',
    'cart.login_required': 'Por favor, faça login para comprar.',
    'checkout.secure_payment': 'Pagamento seguro via Mercado Pago',
    'product.not_found': 'Produto não encontrado',
    'product.select_size': 'Tamanho',
    'product.shipping_info': 'Frete grátis acima de $200.000',
    'product.return_policy': 'Política de devolução de 30 dias',
    'nav.account': 'Conta',
    'nav.orders': 'Meus Pedidos',
    'nav.favorites': 'Favoritos',
    'nav.menu': 'Menu',
    'favorites.login_msg': 'Faça login para ver seus favoritos.',
    'favorites.empty': 'Nenhum item salvo ainda.',
    'favorites.browse': 'Navegar na Loja',
    'footer.address': 'Bogotá, Colômbia',
    'favorites.added': 'Adicionado aos favoritos',
    'favorites.removed': 'Removido dos favoritos',
    'favorites.error_add': 'Erro ao adicionar aos favoritos',
    'favorites.error_remove': 'Erro ao remover dos favoritos',
    'favorites.login_required': 'Faça login para salvar favoritos',
    'checkout.redirecting': 'Redirecionando para o pagamento...',
    'checkout.init_failed': 'Falha na inicialização do pagamento',
    'checkout.missing_fields': 'Campos de envio ausentes',
    'cart.added_success': 'Adicionado ao carrinho',
     // New
    'home.view_all': 'Ver Tudo',
    'filters.title': 'Filtros',
    'filters.gender': 'Gênero',
    'filters.men': 'Homens',
    'filters.women': 'Mulheres',
    'filters.categories': 'Categorias',
    'cat.hoodies': 'Moletons',
    'cat.tshirts': 'Camisetas',
    'cat.pants': 'Calças',
    'cat.footwear': 'Calçados',
    'cat.accessories': 'Acessórios',
     'hero.cta': 'Ver Coleção',
    // Footer
    'footer.about': 'Sobre Nós',
    'footer.description': 'Redefinindo o streetwear com estética futurista.',
    'footer.shop': 'Loja',
    'footer.help': 'Ajuda',
    'footer.legal': 'Legal',
    'footer.links.men': 'Homens',
    'footer.links.women': 'Mulheres',
    'footer.links.sale': 'Ofertas',
    'footer.help.shipping': 'Envios',
    'footer.help.returns': 'Devoluções',
    'footer.help.contact': 'Contato',
    'footer.newsletter': 'Inscrever-se',
    'footer.newsletter.desc': 'Receba as últimas novidades.',
    'footer.rights': 'Todos os direitos reservados.',
    // WhatsApp
    'whatsapp.chat': 'Converse conosco',
    // Checkout
    'checkout.title': 'Finalizar Compra',
    'checkout.shipping': 'Informações de Envio',
    'checkout.name': 'Nome Completo',
    'checkout.address': 'Endereço',
    'checkout.city': 'Cidade',
    'checkout.phone': 'Telefone',
    'checkout.placeholder_name': 'Ex: João Silva',
    'checkout.placeholder_address': 'Ex: Rua 123, 45',
    'checkout.placeholder_phone': 'Ex: 11 91234-5678',
    'checkout.summary': 'Resumo do Pedido',
    'checkout.subtotal': 'Subtotal',
    'checkout.shipping_cost': 'Frete',
    'checkout.total': 'Total',
    'checkout.pay': 'Pagar com Mercado Pago',
    'checkout.processing': 'Processando...',
    'checkout.error': 'Erro ao processar',
    'checkout.select_city': 'Selecione sua cidade',
    'filters.banner.title': 'Oferta de Inverno',
    'filters.banner.desc': 'Até 50% de desconto.',
    'filters.banner.cta': 'Ver Ofertas',
    'nav.dashboard': 'Dashboard',
    'products.details': 'Ver Detalhes',
    'product.quantity': 'Quantidade',
    'shop.no_results': 'Nenhum produto encontrado com estes filtros.',
    'shop.clear_filters': 'Limpar Filtros',
    'nav.orders_tooltip': 'Faça login para ver pedidos',
    'footer.subscribe_btn': 'Inscrever-se',
    'product.size_guide': 'Guia de tamanhos',
    'product.available_stock': 'unidades disponíveis',
    'product.out_of_stock': 'Esgotado',
    'discounts.limited_time': 'Tempo Limitado',
    'discounts.no_active': 'Sem ofertas ativas',
    'discounts.updating_inventory': 'Estamos atualizando nosso estoque. Volte em breve.',
    'discounts.back_to_shop': 'Voltar à Loja',
    'dash.create_product': 'Criar Produto',
    'dash.product_management': 'Gerenciamento de Produtos',
    'dash.manage_inventory': 'Gerenciar estoque da loja',
    'dash.search_products': 'Buscar produtos...',
    'dash.product_name': 'Nome do Produto',
    'dash.category': 'Categoria',
    'dash.new_product': 'Novo Produto',
    'dash.edit_product': 'Editar Produto',
    'dash.product_details': 'Preencha os detalhes do produto',
    'dash.basic_info': 'Informações Básicas',
    'dash.select_category': 'Selecionar categoria',
    'dash.available_sizes': 'Tamanhos Disponíveis',
    'dash.colors': 'Cores',
    'dash.click_add_colors': 'Clique para adicionar cores',
    'dash.product_images': 'Imagens do Produto',
    'dash.click_upload': 'Clique para fazer upload',
    'dash.upload_limit': 'PNG, JPG até 5MB',
    'dash.mark_new': 'Marcar como NOVO',
    'dash.cancel': 'Cancelar',
    'dash.save_product': 'Salvar Produto',
    'dash.uploading': 'Enviando...',
    'dash.no_products': 'Nenhum produto encontrado',
    'dash.add_first': 'Adicione seu primeiro produto!',
    'dash.delete_confirm': 'Tem certeza que deseja excluir este produto?',
    'dash.name': 'Nome do Produto',
    'dash.price': 'Preço',
    'dash.desc': 'Descrição',
    'dash.img': 'URL da Imagem',
    'dash.cat': 'Categoria',
    'dash.gender': 'Gênero',
    'dash.stock': 'Estoque',
    'dash.create_btn': 'Publicar Produto',
    'dash.success': 'Produto criado com sucesso',
    'dash.users': 'Usuários',
    'dash.products': 'Produtos',
    'dash.analytics': 'Análises',
    'dash.orders': 'Pedidos',
    'dash.monitor_performance': 'Monitore o desempenho do seu negócio',
    'dash.revenue': 'Receita',
    'dash.revenue_trend': 'Tendência de Receita',
    'dash.orders_volume': 'Volume de Pedidos',
    'dash.recent_orders': 'Pedidos Recentes',
    'dash.view_all': 'Ver Todos',
    'dash.total_sales': 'Vendas Totais',
    'dash.customers': 'Clientes',
    'dash.avg_order': 'Pedido Médio',
    'dash.order_id': 'ID do Pedido',
    // Dashboard comprehensive translations
    'dash.user_management': 'Gerenciamento de Usuários',
    'dash.user_desc': 'Gerenciar funções e permissões de usuários',
    'dash.search': 'Pesquisar',
    'dash.total_users': 'Total de Usuários',
    'dash.owners': 'Proprietários',
    'dash.regular_users': 'Usuários Regulares',
    'dash.role': 'Função',
    'dash.joined': 'Registrado em',
    'dash.actions': 'Ações',
    'dash.delete_user': 'Excluir usuário',
    'dash.click_toggle': 'Clique para alternar',
    'dash.no_users': 'Nenhum usuário encontrado',
    'dash.warning_zone': 'Zona de administração sensível',
    'dash.role_warning': 'Altere funções apenas para usuários confiáveis. A função Owner tem acesso total ao dashboard.',
    // Orders
    'dash.orders_management': 'Gerenciamento de Pedidos',
    'dash.orders_desc': 'Gerenciar envios e cumprimento de pedidos',
    'dash.total_orders': 'Total de Pedidos',
    'dash.all': 'Todos',
    'dash.pending': 'Pendente',
    'dash.paid': 'Pago',
    'dash.shipped': 'Enviado',
    'dash.delivered': 'Entregue',
    'dash.cancelled': 'Cancelado',
    'dash.customer': 'Cliente',
    'dash.date': 'Data',
    'dash.amount': 'Valor',
    'dash.status': 'Status',
    'dash.phone': 'Telefone',
    'dash.city': 'Cidade',
    'dash.address': 'Endereço',
    'dash.mark_paid': 'Marcar como Pago',
    'dash.ship_order': 'Enviar Pedido',
    'dash.mark_delivered': 'Marcar Entregue',
    'dash.no_orders': 'Nenhum pedido ainda',
    // Additional Dashboard Translations
    'dash.access_denied': 'Acesso Negado',
    'dash.no_permission': 'Você não tem permissão para ver esta página.',
    'dash.user_label': 'Usuário:',
    'dash.role_label': 'Função:',
    'dash.required_role': 'Função Requerida:',
    'dash.go_home': 'Ir para Início',
    'dash.admin': 'Admin',
    'dash.panel': 'Painel de Dashboard',
    'dash.no_data': 'Sem dados',
    'dash.search_placeholder': 'Pesquisar...',
    'dash.user': 'Usuário',
    'dash.search_users': 'Pesquisar usuários...',
    'dash.no_users_search': 'Nenhum usuário encontrado correspondente à sua pesquisa',
    'dash.role_change_confirm': 'Tem certeza de que deseja mudar este usuário para {role}?',
    'dash.error_role_change': 'Erro ao alterar função',
    'dash.delete_confirm_user': '⚠️ Tem CERTEZA de que deseja excluir a conta de {email}?\n\nEsta ação NÃO PODE ser DESFEITA.',
    'dash.error_delete_user': 'Erro ao excluir usuário',
    'dash.search_orders': 'Pesquisar por ID ou cliente...',
    'dash.no_orders_search': 'Nenhum pedido encontrado correspondente à sua pesquisa',
    'dash.customer_label': 'Cliente:',
    'dash.date_label': 'Data:',
    'dash.phone_label': 'Telefone:',
    'dash.city_label': 'Cidade:',
    'dash.address_label': 'Endereço:',
    'dash.error_update_order': 'Erro ao atualizar status do pedido',
    'dash.owner': 'Proprietário',
    'dash.confirm_status_title': 'Confirmar Alteração',
    'dash.confirm_status_desc': 'Tem certeza que deseja alterar o status para {status}?',
    'dash.confirm_btn': 'Confirmar',
    'dash.reviews': 'Avaliações',
    'dash.reviews_title': 'Gestão de Avaliações',
    'dash.reply': 'Responder',
    'dash.delete_review': 'Excluir Avaliação',
    'dash.reply_placeholder': 'Escreva sua resposta pública...',
    'dash.reply_save': 'Publicar Resposta',
    'dash.replied': 'Respondida',


    // Reviews
    'reviews.title': 'Avaliações de Clientes',
    'reviews.write': 'Escrever Avaliação',
    'reviews.rating': 'Classificação',
    'reviews.submit': 'Enviar Avaliação',
    'reviews.login_to_write': 'Faça login para escrever uma avaliação',
    'reviews.no_reviews': 'Ainda não há avaliações. Seja o primeiro!',
    'reviews.success': 'Avaliação enviada com sucesso!',
    'reviews.comment_placeholder': 'Compartilhe sua experiência com este produto...',
    'reviews.based_on': 'Com base em {0} avaliações',
    'reviews.delete': 'Excluir',
    'reviews.already_reviewed': 'Você já avaliou este produto',
    'reviews.delivered_only': 'Receber pedido para avaliar',
    'reviews.rate_btn': 'Avaliar Produto',

    // Profile & Addresses
    'profile.title': 'Meu Perfil',
    'profile.personal': 'Informações Pessoais',
    'profile.addresses': 'Minhas Endereços',
    'profile.security': 'Segurança',
    'profile.save': 'Salvar Alterações',
    'profile.update_success': 'Perfil atualizado com sucesso',
    'profile.password_title': 'Alterar Senha',
    'profile.new_password': 'Nova Senha',
    'profile.confirm_password': 'Confirmar Senha',
    'profile.password_success': 'Senha atualizada com sucesso',

    'address.add': 'Adicionar Endereço',
    'address.edit': 'Editar',
    'address.delete': 'Excluir',
    'address.default': 'Padrão',
    'address.set_default': 'Definir como Padrão',
    'address.name': 'Nome (ex. Casa)',
    'address.recipient': 'Destinatário',
    'address.street': 'Endereço',
    'address.city': 'Cidade',
    'address.phone': 'Telefone',
    'address.save': 'Salvar Endereço',
    'address.no_addresses': 'Nenhum endereço salvo',


    // My Orders
    'my_orders.title': 'Meus Pedidos',
    'my_orders.desc': 'Acompanhe e gerencie suas compras recentes',
    'my_orders.no_orders': 'Nenhum pedido ainda',
    'my_orders.no_orders_desc': 'Parece que você ainda não comprou nada.',
    'my_orders.start_shopping': 'Começar a Comprar',
    'my_orders.total': 'Total',
    'dash.custom': 'Personalizado',
    'dash.no_data_export': 'Não há dados para exportar',

    // New additions
    'filters.price_title': 'Preço',
    'filters.size_title': 'Tamanho',
    'filters.min_placeholder': 'Min',
    'filters.max_placeholder': 'Max',
    'filters.apply': 'Aplicar',
    'cat.caps': 'Bonés',
    'cat.jackets': 'Jaquetas',
    'dash.clear_colors': 'Limpar Tudo',
    'product.promo': 'PROMO',
    'promos.upto_off': 'Até {0}% OFF',
    'dash.gender_unisex': 'Unissex',
    'dash.gender_men': 'Homens',
    'dash.gender_women': 'Mulheres',

    // Payment Result Pages
    'page.pending.title': 'Pagamento Pendente',
    'page.pending.desc': 'Seu pagamento está sendo processado. Notificaremos você assim que for confirmado.',
    'page.pending.check_status': 'Ver Status do Pedido',
    'page.pending.back_home': 'Voltar ao Início',
    'page.success.title': 'Pagamento Realizado!',
    'page.success.desc': 'Obrigado por sua compra. Seu pedido foi confirmado.',
    'page.success.view_order': 'Ver Meu Pedido',
    'page.success.continue_shopping': 'Continuar Comprando',
    'page.failure.title': 'Falha no Pagamento',
    'page.failure.desc': 'Houve um problema ao processar seu pagamento. Por favor, tente novamente.',
    'page.failure.try_again': 'Tentar Novamente',
    'page.failure.contact_support': 'Contatar Suporte',

    // Dashboard Filters
    'dash.all_categories': 'Todas as Categorias',
    'dash.all_sizes': 'Todos os Tamanhos',
    'dash.filter_stock_all': 'Todo o Estoque',
    'dash.filter_in_stock': 'Em Estoque',
    'dash.filter_low_stock': 'Estoque Baixo',
    'dash.filter_out_of_stock': 'Esgotado',
    'dash.filter_min_price': 'Preço Min',
    'dash.filter_max_price': 'Preço Max',
    'dash.filter_rating': 'Classificação Min',
    'dash.rating_label': 'Classificação Inicial (Fixa)',
    'dash.rating_help': 'Estrellas para exibir por padrão',
    'dash.add_product': 'Adicionar Produto',
    'dash.na': 'N/A',
  }
};

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es')

  const t = (key: string) => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
